version: '3.0'
name: ci_cd_dev
services:
  dev:
    container_name: ci_cd_dev
    image: mochrira/dev:7.4.33
    volumes:
      - vhost.conf:/etc/apache2/conf.d/vhost.conf
      - ../:/workspace
    ports:
      - 8092:80